version: '3'
services:

  api:
    image: node:16.15.0
    command: yarn start
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: jack
      POSTGRES_PASSWORD: RaNdOMSt0nGP@assW0rd
      POSTGRES_DB: tweetulator_db
    volumes:
      - ./dockerdb/mount:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
