version: '3'
services:

  db:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: jack
      POSTGRES_PASSWORD: RaNdOMSt0nGP@assW0rd
      POSTGRES_DB: tweetulator_db
    volumes:
      - ./dockerdb/mount:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
